#!/bin/bash
[ -e /usr/bin/patchelf ] || { echo 'install patchelf. apt/dnf/yum install patchelf'; exit 1; }
[ -e /usr/bin/gcc ]      || { echo 'install gcc. apt/dnf/yum install gcc ccache'; exit 1; }
cp -f PathOfBuilding_v2.png PathOfBuilding.png
# --disable-console
python -m nuitka src/PathOfBuilding.py
ls PathOfBuilding

