#!/bin/sh
pyside6-uic PoB_Main_Window.ui -o ../src/PoB_Main_Window.py
pyside6-uic dlgConfig.ui -o ../src/dlg_Config.py
pyside6-uic dlgImport.ui -o ../src/dlg_Import.py
pyside6-uic dlgExport.ui -o ../src/dlg_Export.py
