#!/bin/sh
poetry=$(find ~ -type f -iname poetry | head -n1)
env=$($poetry env list --full-path | awk '/pathofbuilding-python/{print $1}')
${env}/bin/pyside6-uic PoB_Main_Window.ui -o ../src/ui/PoB_Main_Window.py
${env}/bin/pyside6-uic dlgConfig.ui -o ../src/ui/dlg_Config.py
${env}/bin/pyside6-uic dlgBuildImport.ui -o ../src/ui/dlg_BuildImport.py
${env}/bin/pyside6-uic dlgBuildExport.ui -o ../src/ui/dlg_BuildExport.py
${env}/bin/pyside6-uic dlgManageTree.ui -o ../src/ui/dlg_ManageTree.py
${env}/bin/pyside6-uic dlgManageSkills.ui -o ../src/ui/dlg_ManageSkills.py
${env}/bin/pyside6-uic dlgManageItems.ui -o ../src/ui/dlg_ManageItems.py
${env}/bin/pyside6-uic dlgCraftItems.ui -o ../src/ui/dlg_CraftItems.py
