# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PoB_Main_Window.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFontComboBox,
    QFrame, QGraphicsView, QGridLayout, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QSpacerItem, QSpinBox,
    QSplitter, QStatusBar, QTabWidget, QTextEdit,
    QToolBar, QVBoxLayout, QWidget)
import PoB_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1269, 765)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setWindowTitle(u"Path of Building")
        icon = QIcon()
        icon.addFile(u":/Art/Icons/PathOfBuilding.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.action_New = QAction(MainWindow)
        self.action_New.setObjectName(u"action_New")
        icon1 = QIcon()
        iconThemeName = u"appointment-new"
        if QIcon.hasThemeIcon(iconThemeName):
            icon1 = QIcon.fromTheme(iconThemeName)
        else:
            icon1.addFile(u":/Art/Icons/add-folder.png", QSize(), QIcon.Normal, QIcon.Off)
        
        self.action_New.setIcon(icon1)
        self.action_Save = QAction(MainWindow)
        self.action_Save.setObjectName(u"action_Save")
        icon2 = QIcon()
        iconThemeName = u"document-open"
        if QIcon.hasThemeIcon(iconThemeName):
            icon2 = QIcon.fromTheme(iconThemeName)
        else:
            icon2.addFile(u":/Art/Icons/downloads-folder.png", QSize(), QIcon.Normal, QIcon.Off)
        
        self.action_Save.setIcon(icon2)
        self.action_Exit = QAction(MainWindow)
        self.action_Exit.setObjectName(u"action_Exit")
        icon3 = QIcon()
        iconThemeName = u"application-exit"
        if QIcon.hasThemeIcon(iconThemeName):
            icon3 = QIcon.fromTheme(iconThemeName)
        else:
            icon3.addFile(u":/Art/Icons/door-open-out.png", QSize(), QIcon.Normal, QIcon.Off)
        
        self.action_Exit.setIcon(icon3)
        self.action_Open = QAction(MainWindow)
        self.action_Open.setObjectName(u"action_Open")
        icon4 = QIcon()
        icon4.addFile(u":/Art/Icons/opened-folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Open.setIcon(icon4)
        self.action_Theme = QAction(MainWindow)
        self.action_Theme.setObjectName(u"action_Theme")
        self.action_Theme.setCheckable(True)
        self.action_Theme.setChecked(True)
        icon5 = QIcon()
        icon5.addFile(u":/Art/Icons/yin-yang.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Theme.setIcon(icon5)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.mainsplitter = QSplitter(self.centralwidget)
        self.mainsplitter.setObjectName(u"mainsplitter")
        self.mainsplitter.setAutoFillBackground(False)
        self.mainsplitter.setStyleSheet(u"")
        self.mainsplitter.setOrientation(Qt.Horizontal)
        self.frame = QFrame(self.mainsplitter)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(220, 600))
        self.frame.setMaximumSize(QSize(300, 16777215))
        self.frame.setSizeIncrement(QSize(10, 0))
        self.frame.setBaseSize(QSize(200, 0))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.frame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label_Bandits = QLabel(self.frame)
        self.label_Bandits.setObjectName(u"label_Bandits")

        self.gridLayout.addWidget(self.label_Bandits, 0, 0, 1, 1)

        self.combo_Bandits = QComboBox(self.frame)
        self.combo_Bandits.addItem("")
        self.combo_Bandits.addItem("")
        self.combo_Bandits.addItem("")
        self.combo_Bandits.addItem("")
        self.combo_Bandits.setObjectName(u"combo_Bandits")
        sizePolicy1 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.combo_Bandits.sizePolicy().hasHeightForWidth())
        self.combo_Bandits.setSizePolicy(sizePolicy1)
        self.combo_Bandits.setMinimumSize(QSize(180, 0))
        self.combo_Bandits.setMaximumSize(QSize(280, 16777215))
        self.combo_Bandits.setSizeAdjustPolicy(QComboBox.AdjustToContentsOnFirstShow)
        self.combo_Bandits.setMinimumContentsLength(60)
        self.combo_Bandits.setModelColumn(0)

        self.gridLayout.addWidget(self.combo_Bandits, 1, 0, 1, 1)

        self.label_Pantheon = QLabel(self.frame)
        self.label_Pantheon.setObjectName(u"label_Pantheon")
        self.label_Pantheon.setMinimumSize(QSize(0, 0))

        self.gridLayout.addWidget(self.label_Pantheon, 2, 0, 1, 1)

        self.combo_MajorGods = QComboBox(self.frame)
        self.combo_MajorGods.addItem("")
        self.combo_MajorGods.addItem("")
        self.combo_MajorGods.addItem("")
        self.combo_MajorGods.addItem("")
        self.combo_MajorGods.addItem("")
        self.combo_MajorGods.setObjectName(u"combo_MajorGods")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.combo_MajorGods.sizePolicy().hasHeightForWidth())
        self.combo_MajorGods.setSizePolicy(sizePolicy2)
        self.combo_MajorGods.setMinimumSize(QSize(180, 0))
        self.combo_MajorGods.setMaximumSize(QSize(280, 16777215))

        self.gridLayout.addWidget(self.combo_MajorGods, 3, 0, 1, 1)

        self.combo_MinorGods = QComboBox(self.frame)
        self.combo_MinorGods.addItem("")
        self.combo_MinorGods.addItem("")
        self.combo_MinorGods.addItem("")
        self.combo_MinorGods.addItem("")
        self.combo_MinorGods.addItem("")
        self.combo_MinorGods.addItem("")
        self.combo_MinorGods.addItem("")
        self.combo_MinorGods.addItem("")
        self.combo_MinorGods.addItem("")
        self.combo_MinorGods.setObjectName(u"combo_MinorGods")
        sizePolicy2.setHeightForWidth(self.combo_MinorGods.sizePolicy().hasHeightForWidth())
        self.combo_MinorGods.setSizePolicy(sizePolicy2)
        self.combo_MinorGods.setMinimumSize(QSize(180, 0))
        self.combo_MinorGods.setMaximumSize(QSize(280, 16777215))

        self.gridLayout.addWidget(self.combo_MinorGods, 4, 0, 1, 1)

        self.label_MainSkill = QLabel(self.frame)
        self.label_MainSkill.setObjectName(u"label_MainSkill")
        self.label_MainSkill.setMinimumSize(QSize(0, 0))

        self.gridLayout.addWidget(self.label_MainSkill, 5, 0, 1, 1)

        self.combo_MainSkill = QComboBox(self.frame)
        self.combo_MainSkill.setObjectName(u"combo_MainSkill")
        sizePolicy2.setHeightForWidth(self.combo_MainSkill.sizePolicy().hasHeightForWidth())
        self.combo_MainSkill.setSizePolicy(sizePolicy2)
        self.combo_MainSkill.setMinimumSize(QSize(180, 0))
        self.combo_MainSkill.setMaximumSize(QSize(280, 16777215))

        self.gridLayout.addWidget(self.combo_MainSkill, 6, 0, 1, 1)

        self.combo_MainSkillActive = QComboBox(self.frame)
        self.combo_MainSkillActive.setObjectName(u"combo_MainSkillActive")
        sizePolicy2.setHeightForWidth(self.combo_MainSkillActive.sizePolicy().hasHeightForWidth())
        self.combo_MainSkillActive.setSizePolicy(sizePolicy2)
        self.combo_MainSkillActive.setMinimumSize(QSize(180, 0))
        self.combo_MainSkillActive.setMaximumSize(QSize(280, 16777215))

        self.gridLayout.addWidget(self.combo_MainSkillActive, 7, 0, 1, 1)

        self.listStatistics = QListWidget(self.frame)
        self.listStatistics.setObjectName(u"listStatistics")
        self.listStatistics.setMinimumSize(QSize(180, 0))

        self.gridLayout.addWidget(self.listStatistics, 8, 0, 1, 1)

        self.mainsplitter.addWidget(self.frame)
        self.tabWidget = QTabWidget(self.mainsplitter)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy3.setHorizontalStretch(2)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy3)
        self.tabWidget.setMinimumSize(QSize(600, 500))
        self.tabWidget.setStyleSheet(u"")
        self.tabTree = QWidget()
        self.tabTree.setObjectName(u"tabTree")
        self.horizontalLayout_2 = QHBoxLayout(self.tabTree)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.graphicsView = QGraphicsView(self.tabTree)
        self.graphicsView.setObjectName(u"graphicsView")

        self.horizontalLayout_2.addWidget(self.graphicsView)

        self.tabWidget.addTab(self.tabTree, "")
        self.tabSkills = QWidget()
        self.tabSkills.setObjectName(u"tabSkills")
        self.horizontalLayout_3 = QHBoxLayout(self.tabSkills)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.frame_SkillsTabLeft = QFrame(self.tabSkills)
        self.frame_SkillsTabLeft.setObjectName(u"frame_SkillsTabLeft")
        sizePolicy4 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(4)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.frame_SkillsTabLeft.sizePolicy().hasHeightForWidth())
        self.frame_SkillsTabLeft.setSizePolicy(sizePolicy4)
        self.frame_SkillsTabLeft.setMinimumSize(QSize(400, 0))
        self.frame_SkillsTabLeft.setFrameShape(QFrame.StyledPanel)
        self.frame_SkillsTabLeft.setFrameShadow(QFrame.Raised)
        self.label_SocketGroups = QLabel(self.frame_SkillsTabLeft)
        self.label_SocketGroups.setObjectName(u"label_SocketGroups")
        self.label_SocketGroups.setGeometry(QRect(10, 40, 100, 22))
        self.label_SkillSet = QLabel(self.frame_SkillsTabLeft)
        self.label_SkillSet.setObjectName(u"label_SkillSet")
        self.label_SkillSet.setGeometry(QRect(10, 10, 100, 22))
        self.combo_SkillSet = QComboBox(self.frame_SkillsTabLeft)
        self.combo_SkillSet.setObjectName(u"combo_SkillSet")
        self.combo_SkillSet.setGeometry(QRect(110, 10, 180, 22))
        self.btn_SkillsManage = QPushButton(self.frame_SkillsTabLeft)
        self.btn_SkillsManage.setObjectName(u"btn_SkillsManage")
        self.btn_SkillsManage.setGeometry(QRect(310, 10, 75, 22))
        self.btn_SkillsDelete = QPushButton(self.frame_SkillsTabLeft)
        self.btn_SkillsDelete.setObjectName(u"btn_SkillsDelete")
        self.btn_SkillsDelete.setGeometry(QRect(210, 40, 75, 22))
        self.btn_SkillsDeleteAll = QPushButton(self.frame_SkillsTabLeft)
        self.btn_SkillsDeleteAll.setObjectName(u"btn_SkillsDeleteAll")
        self.btn_SkillsDeleteAll.setGeometry(QRect(310, 40, 75, 22))
        self.btn_SkillsNew = QPushButton(self.frame_SkillsTabLeft)
        self.btn_SkillsNew.setObjectName(u"btn_SkillsNew")
        self.btn_SkillsNew.setGeometry(QRect(110, 40, 75, 22))
        self.list_Skills = QListWidget(self.frame_SkillsTabLeft)
        self.list_Skills.setObjectName(u"list_Skills")
        self.list_Skills.setGeometry(QRect(10, 70, 375, 311))
        self.label_Usage_Hints = QLabel(self.frame_SkillsTabLeft)
        self.label_Usage_Hints.setObjectName(u"label_Usage_Hints")
        self.label_Usage_Hints.setGeometry(QRect(10, 385, 375, 91))
        self.label_Usage_Hints.setScaledContents(True)
        self.group_SkillTabLeft = QGroupBox(self.frame_SkillsTabLeft)
        self.group_SkillTabLeft.setObjectName(u"group_SkillTabLeft")
        self.group_SkillTabLeft.setGeometry(QRect(0, 480, 400, 165))
        self.group_SkillTabLeft.setMinimumSize(QSize(375, 165))
        self.label = QLabel(self.group_SkillTabLeft)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 15, 170, 22))
        self.label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_2 = QLabel(self.group_SkillTabLeft)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 170, 22))
        self.label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_3 = QLabel(self.group_SkillTabLeft)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 65, 170, 22))
        self.label_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_4 = QLabel(self.group_SkillTabLeft)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 90, 170, 22))
        self.label_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_5 = QLabel(self.group_SkillTabLeft)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 115, 170, 22))
        self.label_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_6 = QLabel(self.group_SkillTabLeft)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 140, 170, 22))
        self.label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_2 = QComboBox(self.group_SkillTabLeft)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(220, 15, 171, 22))
        self.check_MatchToLevel = QCheckBox(self.group_SkillTabLeft)
        self.check_MatchToLevel.setObjectName(u"check_MatchToLevel")
        self.check_MatchToLevel.setGeometry(QRect(190, 40, 75, 20))
        self.spin_DefaultGemLevel = QSpinBox(self.group_SkillTabLeft)
        self.spin_DefaultGemLevel.setObjectName(u"spin_DefaultGemLevel")
        self.spin_DefaultGemLevel.setGeometry(QRect(190, 65, 42, 22))
        self.spin_DefaultGemLevel.setMinimum(1)
        self.spin_DefaultGemLevel.setMaximum(20)
        self.spin_DefaultGemQuality = QSpinBox(self.group_SkillTabLeft)
        self.spin_DefaultGemQuality.setObjectName(u"spin_DefaultGemQuality")
        self.spin_DefaultGemQuality.setGeometry(QRect(190, 90, 42, 22))
        self.spin_DefaultGemQuality.setMaximum(20)
        self.combo_ShowSupportGems = QComboBox(self.group_SkillTabLeft)
        self.combo_ShowSupportGems.setObjectName(u"combo_ShowSupportGems")
        self.combo_ShowSupportGems.setGeometry(QRect(190, 115, 202, 22))
        self.check_ShowGemQualityVariants = QCheckBox(self.group_SkillTabLeft)
        self.check_ShowGemQualityVariants.setObjectName(u"check_ShowGemQualityVariants")
        self.check_ShowGemQualityVariants.setGeometry(QRect(190, 140, 75, 20))
        self.check_SortByDPS = QCheckBox(self.group_SkillTabLeft)
        self.check_SortByDPS.setObjectName(u"check_SortByDPS")
        self.check_SortByDPS.setGeometry(QRect(190, 15, 75, 20))
        self.widget_4 = QWidget(self.frame_SkillsTabLeft)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(400, 190, 500, 40))
        self.check_GemEnabled4 = QCheckBox(self.widget_4)
        self.check_GemEnabled4.setObjectName(u"check_GemEnabled4")
        self.check_GemEnabled4.setGeometry(QRect(9, 13, 16, 16))
        self.check_GemEnabled4.setChecked(True)
        self.combo_GemList4 = QComboBox(self.widget_4)
        self.combo_GemList4.setObjectName(u"combo_GemList4")
        self.combo_GemList4.setGeometry(QRect(30, 10, 170, 22))
        self.combo_GemList4.setMinimumSize(QSize(170, 0))
        self.spin_GemLevel4 = QSpinBox(self.widget_4)
        self.spin_GemLevel4.setObjectName(u"spin_GemLevel4")
        self.spin_GemLevel4.setGeometry(QRect(210, 10, 42, 22))
        self.spin_GemLevel4.setMinimumSize(QSize(42, 0))
        self.spin_GemLevel4.setMinimum(1)
        self.spin_GemLevel4.setMaximum(20)
        self.spin_GemQuality4 = QSpinBox(self.widget_4)
        self.spin_GemQuality4.setObjectName(u"spin_GemQuality4")
        self.spin_GemQuality4.setGeometry(QRect(260, 10, 42, 22))
        self.spin_GemQuality4.setMinimumSize(QSize(42, 0))
        self.spin_GemQuality4.setMaximum(20)
        self.combo_GemVariant4 = QComboBox(self.widget_4)
        self.combo_GemVariant4.addItem("")
        self.combo_GemVariant4.addItem("")
        self.combo_GemVariant4.setObjectName(u"combo_GemVariant4")
        self.combo_GemVariant4.setGeometry(QRect(310, 10, 80, 22))
        self.check_GemEnabled4_2 = QCheckBox(self.widget_4)
        self.check_GemEnabled4_2.setObjectName(u"check_GemEnabled4_2")
        self.check_GemEnabled4_2.setGeometry(QRect(415, 13, 16, 16))
        self.check_GemEnabled4_2.setChecked(True)
        self.spin_GemCount4 = QSpinBox(self.widget_4)
        self.spin_GemCount4.setObjectName(u"spin_GemCount4")
        self.spin_GemCount4.setGeometry(QRect(450, 9, 42, 22))
        self.spin_GemCount4.setMinimum(1)
        self.spin_GemCount4.setMaximum(20)
        self.combo_SocketedIn = QComboBox(self.frame_SkillsTabLeft)
        self.combo_SocketedIn.setObjectName(u"combo_SocketedIn")
        self.combo_SocketedIn.setGeometry(QRect(480, 40, 171, 22))
        self.label_Variant = QLabel(self.frame_SkillsTabLeft)
        self.label_Variant.setObjectName(u"label_Variant")
        self.label_Variant.setGeometry(QRect(710, 80, 40, 22))
        self.check_SocketGroupEnabled = QCheckBox(self.frame_SkillsTabLeft)
        self.check_SocketGroupEnabled.setObjectName(u"check_SocketGroupEnabled")
        self.check_SocketGroupEnabled.setGeometry(QRect(660, 40, 75, 20))
        self.check_SocketGroupEnabled.setChecked(False)
        self.label_SocketedIn = QLabel(self.frame_SkillsTabLeft)
        self.label_SocketedIn.setObjectName(u"label_SocketedIn")
        self.label_SocketedIn.setGeometry(QRect(410, 40, 71, 22))
        self.label_Enabled = QLabel(self.frame_SkillsTabLeft)
        self.label_Enabled.setObjectName(u"label_Enabled")
        self.label_Enabled.setGeometry(QRect(800, 80, 41, 22))
        self.label_Count = QLabel(self.frame_SkillsTabLeft)
        self.label_Count.setObjectName(u"label_Count")
        self.label_Count.setGeometry(QRect(850, 80, 40, 22))
        self.lineEdit_SkillLabel = QLineEdit(self.frame_SkillsTabLeft)
        self.lineEdit_SkillLabel.setObjectName(u"lineEdit_SkillLabel")
        self.lineEdit_SkillLabel.setGeometry(QRect(480, 10, 391, 22))
        self.label_SkillLabel = QLabel(self.frame_SkillsTabLeft)
        self.label_SkillLabel.setObjectName(u"label_SkillLabel")
        self.label_SkillLabel.setGeometry(QRect(410, 10, 61, 22))
        self.label_Level = QLabel(self.frame_SkillsTabLeft)
        self.label_Level.setObjectName(u"label_Level")
        self.label_Level.setGeometry(QRect(610, 80, 40, 22))
        self.widget = QWidget(self.frame_SkillsTabLeft)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(400, 100, 500, 40))
        self.check_GemEnabled1 = QCheckBox(self.widget)
        self.check_GemEnabled1.setObjectName(u"check_GemEnabled1")
        self.check_GemEnabled1.setGeometry(QRect(10, 10, 20, 20))
        self.check_GemEnabled1.setChecked(True)
        self.combo_GemList1 = QComboBox(self.widget)
        self.combo_GemList1.setObjectName(u"combo_GemList1")
        self.combo_GemList1.setGeometry(QRect(30, 10, 171, 22))
        self.spin_GemLevel1 = QSpinBox(self.widget)
        self.spin_GemLevel1.setObjectName(u"spin_GemLevel1")
        self.spin_GemLevel1.setGeometry(QRect(210, 10, 42, 22))
        self.spin_GemLevel1.setMinimum(1)
        self.spin_GemLevel1.setMaximum(20)
        self.spin_GemQuality1 = QSpinBox(self.widget)
        self.spin_GemQuality1.setObjectName(u"spin_GemQuality1")
        self.spin_GemQuality1.setGeometry(QRect(260, 10, 42, 22))
        self.spin_GemQuality1.setMaximum(20)
        self.combo_GemVariant1 = QComboBox(self.widget)
        self.combo_GemVariant1.addItem("")
        self.combo_GemVariant1.addItem("")
        self.combo_GemVariant1.setObjectName(u"combo_GemVariant1")
        self.combo_GemVariant1.setGeometry(QRect(310, 10, 80, 22))
        self.check_GemEnabled1_2 = QCheckBox(self.widget)
        self.check_GemEnabled1_2.setObjectName(u"check_GemEnabled1_2")
        self.check_GemEnabled1_2.setGeometry(QRect(415, 10, 20, 20))
        self.check_GemEnabled1_2.setChecked(True)
        self.spin_GemCount1 = QSpinBox(self.widget)
        self.spin_GemCount1.setObjectName(u"spin_GemCount1")
        self.spin_GemCount1.setGeometry(QRect(450, 10, 42, 22))
        self.spin_GemCount1.setMinimum(1)
        self.spin_GemCount1.setMaximum(20)
        self.label_GemName = QLabel(self.frame_SkillsTabLeft)
        self.label_GemName.setObjectName(u"label_GemName")
        self.label_GemName.setGeometry(QRect(430, 80, 70, 22))
        self.check_SocketGroup_FullDPS = QCheckBox(self.frame_SkillsTabLeft)
        self.check_SocketGroup_FullDPS.setObjectName(u"check_SocketGroup_FullDPS")
        self.check_SocketGroup_FullDPS.setGeometry(QRect(750, 40, 130, 20))
        self.check_SocketGroup_FullDPS.setChecked(False)
        self.widget_3 = QWidget(self.frame_SkillsTabLeft)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(400, 160, 500, 40))
        self.check_GemEnabled3 = QCheckBox(self.widget_3)
        self.check_GemEnabled3.setObjectName(u"check_GemEnabled3")
        self.check_GemEnabled3.setGeometry(QRect(10, 10, 20, 20))
        self.check_GemEnabled3.setChecked(True)
        self.combo_GemList3 = QComboBox(self.widget_3)
        self.combo_GemList3.setObjectName(u"combo_GemList3")
        self.combo_GemList3.setGeometry(QRect(30, 10, 171, 22))
        self.spin_GemLevel3 = QSpinBox(self.widget_3)
        self.spin_GemLevel3.setObjectName(u"spin_GemLevel3")
        self.spin_GemLevel3.setGeometry(QRect(210, 10, 42, 22))
        self.spin_GemLevel3.setMinimum(1)
        self.spin_GemLevel3.setMaximum(20)
        self.spin_GemQuality3 = QSpinBox(self.widget_3)
        self.spin_GemQuality3.setObjectName(u"spin_GemQuality3")
        self.spin_GemQuality3.setGeometry(QRect(260, 10, 42, 22))
        self.spin_GemQuality3.setMaximum(20)
        self.combo_GemVariant3 = QComboBox(self.widget_3)
        self.combo_GemVariant3.addItem("")
        self.combo_GemVariant3.addItem("")
        self.combo_GemVariant3.setObjectName(u"combo_GemVariant3")
        self.combo_GemVariant3.setGeometry(QRect(310, 10, 80, 22))
        self.check_GemEnabled3_2 = QCheckBox(self.widget_3)
        self.check_GemEnabled3_2.setObjectName(u"check_GemEnabled3_2")
        self.check_GemEnabled3_2.setGeometry(QRect(415, 10, 20, 20))
        self.check_GemEnabled3_2.setChecked(True)
        self.spin_GemCount3 = QSpinBox(self.widget_3)
        self.spin_GemCount3.setObjectName(u"spin_GemCount3")
        self.spin_GemCount3.setGeometry(QRect(450, 10, 42, 22))
        self.spin_GemCount3.setMinimum(1)
        self.spin_GemCount3.setMaximum(20)
        self.widget_2 = QWidget(self.frame_SkillsTabLeft)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(400, 130, 500, 40))
        self.check_GemEnabled2 = QCheckBox(self.widget_2)
        self.check_GemEnabled2.setObjectName(u"check_GemEnabled2")
        self.check_GemEnabled2.setGeometry(QRect(10, 10, 20, 20))
        self.check_GemEnabled2.setChecked(True)
        self.combo_GemList2 = QComboBox(self.widget_2)
        self.combo_GemList2.setObjectName(u"combo_GemList2")
        self.combo_GemList2.setGeometry(QRect(30, 10, 171, 22))
        self.spin_GemLevel2 = QSpinBox(self.widget_2)
        self.spin_GemLevel2.setObjectName(u"spin_GemLevel2")
        self.spin_GemLevel2.setGeometry(QRect(210, 10, 42, 22))
        self.spin_GemLevel2.setMinimum(1)
        self.spin_GemLevel2.setMaximum(20)
        self.spin_GemQuality2 = QSpinBox(self.widget_2)
        self.spin_GemQuality2.setObjectName(u"spin_GemQuality2")
        self.spin_GemQuality2.setGeometry(QRect(260, 10, 42, 22))
        self.spin_GemQuality2.setMaximum(20)
        self.combo_GemVariant2 = QComboBox(self.widget_2)
        self.combo_GemVariant2.addItem("")
        self.combo_GemVariant2.addItem("")
        self.combo_GemVariant2.setObjectName(u"combo_GemVariant2")
        self.combo_GemVariant2.setGeometry(QRect(310, 10, 80, 22))
        self.check_GemEnabled2_2 = QCheckBox(self.widget_2)
        self.check_GemEnabled2_2.setObjectName(u"check_GemEnabled2_2")
        self.check_GemEnabled2_2.setGeometry(QRect(415, 10, 20, 20))
        self.check_GemEnabled2_2.setChecked(True)
        self.spin_GemCount2 = QSpinBox(self.widget_2)
        self.spin_GemCount2.setObjectName(u"spin_GemCount2")
        self.spin_GemCount2.setGeometry(QRect(450, 10, 42, 22))
        self.spin_GemCount2.setMinimum(1)
        self.spin_GemCount2.setMaximum(20)
        self.label_Quality = QLabel(self.frame_SkillsTabLeft)
        self.label_Quality.setObjectName(u"label_Quality")
        self.label_Quality.setGeometry(QRect(660, 80, 40, 22))
        self.widget_5 = QWidget(self.frame_SkillsTabLeft)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(400, 220, 500, 40))
        self.check_GemEnabled5 = QCheckBox(self.widget_5)
        self.check_GemEnabled5.setObjectName(u"check_GemEnabled5")
        self.check_GemEnabled5.setGeometry(QRect(10, 10, 20, 20))
        self.check_GemEnabled5.setChecked(True)
        self.combo_GemList5 = QComboBox(self.widget_5)
        self.combo_GemList5.setObjectName(u"combo_GemList5")
        self.combo_GemList5.setGeometry(QRect(30, 10, 171, 22))
        self.spin_GemLevel5 = QSpinBox(self.widget_5)
        self.spin_GemLevel5.setObjectName(u"spin_GemLevel5")
        self.spin_GemLevel5.setGeometry(QRect(210, 10, 42, 22))
        self.spin_GemLevel5.setMinimum(1)
        self.spin_GemLevel5.setMaximum(20)
        self.spin_GemQuality5 = QSpinBox(self.widget_5)
        self.spin_GemQuality5.setObjectName(u"spin_GemQuality5")
        self.spin_GemQuality5.setGeometry(QRect(260, 10, 42, 22))
        self.spin_GemQuality5.setMaximum(20)
        self.combo_GemVariant5 = QComboBox(self.widget_5)
        self.combo_GemVariant5.addItem("")
        self.combo_GemVariant5.addItem("")
        self.combo_GemVariant5.setObjectName(u"combo_GemVariant5")
        self.combo_GemVariant5.setGeometry(QRect(310, 10, 80, 22))
        self.check_GemEnabled5_2 = QCheckBox(self.widget_5)
        self.check_GemEnabled5_2.setObjectName(u"check_GemEnabled5_2")
        self.check_GemEnabled5_2.setGeometry(QRect(415, 10, 20, 20))
        self.check_GemEnabled5_2.setChecked(True)
        self.spin_GemCount5 = QSpinBox(self.widget_5)
        self.spin_GemCount5.setObjectName(u"spin_GemCount5")
        self.spin_GemCount5.setGeometry(QRect(450, 10, 42, 22))
        self.spin_GemCount5.setMinimum(1)
        self.spin_GemCount5.setMaximum(20)
        self.widget_6 = QWidget(self.frame_SkillsTabLeft)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(400, 250, 500, 40))
        self.check_GemEnabled6 = QCheckBox(self.widget_6)
        self.check_GemEnabled6.setObjectName(u"check_GemEnabled6")
        self.check_GemEnabled6.setGeometry(QRect(10, 10, 20, 20))
        self.check_GemEnabled6.setChecked(True)
        self.combo_GemList6 = QComboBox(self.widget_6)
        self.combo_GemList6.setObjectName(u"combo_GemList6")
        self.combo_GemList6.setGeometry(QRect(30, 10, 171, 22))
        self.spin_GemLevel6 = QSpinBox(self.widget_6)
        self.spin_GemLevel6.setObjectName(u"spin_GemLevel6")
        self.spin_GemLevel6.setGeometry(QRect(210, 10, 42, 22))
        self.spin_GemLevel6.setMinimum(1)
        self.spin_GemLevel6.setMaximum(20)
        self.spin_GemQuality6 = QSpinBox(self.widget_6)
        self.spin_GemQuality6.setObjectName(u"spin_GemQuality6")
        self.spin_GemQuality6.setGeometry(QRect(260, 10, 42, 22))
        self.spin_GemQuality6.setMaximum(20)
        self.combo_GemVariant6 = QComboBox(self.widget_6)
        self.combo_GemVariant6.addItem("")
        self.combo_GemVariant6.addItem("")
        self.combo_GemVariant6.setObjectName(u"combo_GemVariant6")
        self.combo_GemVariant6.setGeometry(QRect(310, 10, 80, 22))
        self.check_GemEnabled6_2 = QCheckBox(self.widget_6)
        self.check_GemEnabled6_2.setObjectName(u"check_GemEnabled6_2")
        self.check_GemEnabled6_2.setGeometry(QRect(415, 10, 20, 20))
        self.check_GemEnabled6_2.setChecked(True)
        self.spin_GemCount6 = QSpinBox(self.widget_6)
        self.spin_GemCount6.setObjectName(u"spin_GemCount6")
        self.spin_GemCount6.setGeometry(QRect(450, 10, 42, 22))
        self.spin_GemCount6.setMinimum(1)
        self.spin_GemCount6.setMaximum(20)

        self.horizontalLayout_3.addWidget(self.frame_SkillsTabLeft)

        self.tabWidget.addTab(self.tabSkills, "")
        self.tabItems = QWidget()
        self.tabItems.setObjectName(u"tabItems")
        self.tabWidget.addTab(self.tabItems, "")
        self.tabNotes = QWidget()
        self.tabNotes.setObjectName(u"tabNotes")
        self.verticalLayout = QVBoxLayout(self.tabNotes)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.combo_Notes_Font = QFontComboBox(self.tabNotes)
        self.combo_Notes_Font.setObjectName(u"combo_Notes_Font")
        self.combo_Notes_Font.setMinimumSize(QSize(200, 0))
        self.combo_Notes_Font.setEditable(False)

        self.horizontalLayout_4.addWidget(self.combo_Notes_Font)

        self.spin_Notes_FontSize = QSpinBox(self.tabNotes)
        self.spin_Notes_FontSize.setObjectName(u"spin_Notes_FontSize")
        self.spin_Notes_FontSize.setMinimumSize(QSize(35, 0))
        self.spin_Notes_FontSize.setMinimum(3)
        self.spin_Notes_FontSize.setMaximum(50)
        self.spin_Notes_FontSize.setValue(15)

        self.horizontalLayout_4.addWidget(self.spin_Notes_FontSize)

        self.combo_Notes_Colour = QComboBox(self.tabNotes)
        self.combo_Notes_Colour.setObjectName(u"combo_Notes_Colour")
        self.combo_Notes_Colour.setMinimumSize(QSize(140, 0))

        self.horizontalLayout_4.addWidget(self.combo_Notes_Colour)

        self.horizontalSpacer = QSpacerItem(90, 20, QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer)


        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.textEdit_Notes = QTextEdit(self.tabNotes)
        self.textEdit_Notes.setObjectName(u"textEdit_Notes")
        self.textEdit_Notes.setLineWrapMode(QTextEdit.NoWrap)

        self.verticalLayout.addWidget(self.textEdit_Notes)

        self.tabWidget.addTab(self.tabNotes, "")
        self.mainsplitter.addWidget(self.tabWidget)

        self.horizontalLayout.addWidget(self.mainsplitter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1269, 22))
        self.menubar.setMinimumSize(QSize(400, 0))
        self.menubar.setMaximumSize(QSize(16777215, 16777215))
        self.menu_Builds = QMenu(self.menubar)
        self.menu_Builds.setObjectName(u"menu_Builds")
        self.menu_View = QMenu(self.menubar)
        self.menu_View.setObjectName(u"menu_View")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setAllowedAreas(Qt.BottomToolBarArea|Qt.TopToolBarArea)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menu_Builds.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menu_Builds.addAction(self.action_New)
        self.menu_Builds.addAction(self.action_Open)
        self.menu_Builds.addAction(self.action_Save)
        self.menu_Builds.addSeparator()
        self.menu_Builds.addAction(self.action_Exit)
        self.menu_Builds.addSeparator()
        self.menu_View.addAction(self.action_Theme)
        self.toolBar.addAction(self.action_New)
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.action_Save)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Theme)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.action_Exit.triggered.connect(MainWindow.close)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.action_New.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(tooltip)
        self.action_New.setToolTip(QCoreApplication.translate("MainWindow", u"Start a new build", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_New.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_Save.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.action_Save.setToolTip(QCoreApplication.translate("MainWindow", u"Save this build", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Save.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_Exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(tooltip)
        self.action_Exit.setToolTip(QCoreApplication.translate("MainWindow", u"Exit Path of Building", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Exit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_Open.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.action_Open.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_Theme.setText(QCoreApplication.translate("MainWindow", u"Light", None))
#if QT_CONFIG(tooltip)
        self.action_Theme.setToolTip(QCoreApplication.translate("MainWindow", u"Change the theme between the light and the dark", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.action_Theme.setWhatsThis(QCoreApplication.translate("MainWindow", u"light", None))
#endif // QT_CONFIG(whatsthis)
        self.label_Bandits.setText(QCoreApplication.translate("MainWindow", u"Bandits:", None))
        self.combo_Bandits.setItemText(0, QCoreApplication.translate("MainWindow", u"2 Passives Points", None))
        self.combo_Bandits.setItemText(1, QCoreApplication.translate("MainWindow", u"Oak (Life Regen, Phys.Dmg. Reduction, Phys.Dmg)", None))
        self.combo_Bandits.setItemText(2, QCoreApplication.translate("MainWindow", u"Kraityn (Attack/Cast Speed, Avoid Elemental Ailments, Move Speed)", None))
        self.combo_Bandits.setItemText(3, QCoreApplication.translate("MainWindow", u"Alira (Mana Regen, Crit Multiplier, Resists)", None))

        self.combo_Bandits.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Make  a Selection", None))
        self.label_Pantheon.setText(QCoreApplication.translate("MainWindow", u"The Pantheon:", None))
        self.combo_MajorGods.setItemText(0, QCoreApplication.translate("MainWindow", u"Nothing", None))
        self.combo_MajorGods.setItemText(1, QCoreApplication.translate("MainWindow", u"Soul of the Brine King", None))
        self.combo_MajorGods.setItemText(2, QCoreApplication.translate("MainWindow", u"Soul of Lunaris", None))
        self.combo_MajorGods.setItemText(3, QCoreApplication.translate("MainWindow", u"Soul of Solaris", None))
        self.combo_MajorGods.setItemText(4, QCoreApplication.translate("MainWindow", u"Soul of Arakaali", None))

        self.combo_MajorGods.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Make  a Selection", None))
        self.combo_MinorGods.setItemText(0, QCoreApplication.translate("MainWindow", u"Nothing", None))
        self.combo_MinorGods.setItemText(1, QCoreApplication.translate("MainWindow", u"Soul of Gruthkul", None))
        self.combo_MinorGods.setItemText(2, QCoreApplication.translate("MainWindow", u"Soul of Yugul", None))
        self.combo_MinorGods.setItemText(3, QCoreApplication.translate("MainWindow", u"Soul of Abberath", None))
        self.combo_MinorGods.setItemText(4, QCoreApplication.translate("MainWindow", u"Soul of Tukohama", None))
        self.combo_MinorGods.setItemText(5, QCoreApplication.translate("MainWindow", u"Soul of Garukhan", None))
        self.combo_MinorGods.setItemText(6, QCoreApplication.translate("MainWindow", u"Soul of Ralakesh", None))
        self.combo_MinorGods.setItemText(7, QCoreApplication.translate("MainWindow", u"Soul of Ryslatha", None))
        self.combo_MinorGods.setItemText(8, QCoreApplication.translate("MainWindow", u"Soul of Shakari", None))

        self.combo_MinorGods.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Make  a Selection", None))
        self.label_MainSkill.setText(QCoreApplication.translate("MainWindow", u"Main Skill:", None))
        self.combo_MainSkill.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Skill", None))
        self.combo_MainSkillActive.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Skill", None))
#if QT_CONFIG(accessibility)
        self.tabWidget.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTree), QCoreApplication.translate("MainWindow", u"&Tree", None))
        self.label_SocketGroups.setText(QCoreApplication.translate("MainWindow", u"Socket Groups:", None))
        self.label_SkillSet.setText(QCoreApplication.translate("MainWindow", u"Skill Set: ", None))
        self.btn_SkillsManage.setText(QCoreApplication.translate("MainWindow", u"Manage", None))
        self.btn_SkillsDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.btn_SkillsDeleteAll.setText(QCoreApplication.translate("MainWindow", u"Delete All", None))
        self.btn_SkillsNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.label_Usage_Hints.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><span style=\" font-size:9pt;\">Usage Hints:<br>- You can copy/paste socket groups using Ctrl-C and Ctrl-V.<br>- Ctrl-Left click to enable and disable socket groups.<br>- Ctrl-Right click to include/exclude in FullDPS calculations.<br>- Right click to set as the Main skill group.</span></body></html>", None))
        self.group_SkillTabLeft.setTitle(QCoreApplication.translate("MainWindow", u"Gem Options", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Sort Gems by DPS", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Match Gems to Character Level", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Default Gem Level", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Default Gem Quality", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Show Support Gems", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Show Gem Quality Variants", None))
        self.check_MatchToLevel.setText("")
        self.check_ShowGemQualityVariants.setText("")
        self.check_SortByDPS.setText("")
        self.check_GemEnabled4.setText("")
        self.combo_GemVariant4.setItemText(0, QCoreApplication.translate("MainWindow", u"Default", None))
        self.combo_GemVariant4.setItemText(1, QCoreApplication.translate("MainWindow", u"Anomolous", None))

        self.check_GemEnabled4_2.setText("")
        self.label_Variant.setText(QCoreApplication.translate("MainWindow", u"Variant", None))
        self.check_SocketGroupEnabled.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.label_SocketedIn.setText(QCoreApplication.translate("MainWindow", u"Socketed In:", None))
        self.label_Enabled.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.label_Count.setText(QCoreApplication.translate("MainWindow", u"Count", None))
        self.label_SkillLabel.setText(QCoreApplication.translate("MainWindow", u"Skill Label:", None))
        self.label_Level.setText(QCoreApplication.translate("MainWindow", u"Level:", None))
        self.check_GemEnabled1.setText("")
        self.combo_GemVariant1.setItemText(0, QCoreApplication.translate("MainWindow", u"Default", None))
        self.combo_GemVariant1.setItemText(1, QCoreApplication.translate("MainWindow", u"Anomolous", None))

        self.check_GemEnabled1_2.setText("")
        self.label_GemName.setText(QCoreApplication.translate("MainWindow", u"Gem Name:", None))
        self.check_SocketGroup_FullDPS.setText(QCoreApplication.translate("MainWindow", u"Include in Full DPS", None))
        self.check_GemEnabled3.setText("")
        self.combo_GemVariant3.setItemText(0, QCoreApplication.translate("MainWindow", u"Default", None))
        self.combo_GemVariant3.setItemText(1, QCoreApplication.translate("MainWindow", u"Anomolous", None))

        self.check_GemEnabled3_2.setText("")
        self.check_GemEnabled2.setText("")
        self.combo_GemVariant2.setItemText(0, QCoreApplication.translate("MainWindow", u"Default", None))
        self.combo_GemVariant2.setItemText(1, QCoreApplication.translate("MainWindow", u"Anomolous", None))

        self.check_GemEnabled2_2.setText("")
        self.label_Quality.setText(QCoreApplication.translate("MainWindow", u"Quality", None))
        self.check_GemEnabled5.setText("")
        self.combo_GemVariant5.setItemText(0, QCoreApplication.translate("MainWindow", u"Default", None))
        self.combo_GemVariant5.setItemText(1, QCoreApplication.translate("MainWindow", u"Anomolous", None))

        self.check_GemEnabled5_2.setText("")
        self.check_GemEnabled6.setText("")
        self.combo_GemVariant6.setItemText(0, QCoreApplication.translate("MainWindow", u"Default", None))
        self.combo_GemVariant6.setItemText(1, QCoreApplication.translate("MainWindow", u"Anomolous", None))

        self.check_GemEnabled6_2.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSkills), QCoreApplication.translate("MainWindow", u"&Skills", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabItems), QCoreApplication.translate("MainWindow", u"&Items", None))
        self.combo_Notes_Font.setCurrentText(QCoreApplication.translate("MainWindow", u"Times New Roman", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), QCoreApplication.translate("MainWindow", u"&Notes", None))
        self.menu_Builds.setTitle(QCoreApplication.translate("MainWindow", u"&Builds", None))
        self.menu_View.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        pass
    # retranslateUi

